[project]
authors = ["Andreas Trawöger <atrawog@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mkconnect-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
jupyterlab = ">=4.3.5,<5"
ipywidgets = ">=8.1.5,<9"
